version: '3.7'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    restart: always
    ports:
      - 26379:26379
    volumes:
      - ./redis-sentinel-1/redis.conf:/usr/local/etc/redis/sentinel.conf