version: '3'
services:
  envoygateway:
    build: Envoy/
    ports:
      - "9090:9090"
      - "9443:9443"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml:rw
      - ./Envoy/certs:/etc/envoy/certs:rw
  simpleapp:
    build: SampleApp/
    ports:
      - "8082:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"