version: '3'
services:
  envoygateway:
    build: Envoy/
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.50.162:12201"
        tag: "envoygateway"
  weatherservice1:
    build: WeatherService/
    ports:
      - "8082:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.50.162:12201"
        tag: "weatherservice1"  
  weatherservice2:
    build: WeatherService/
    ports:
      - "8084:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"  
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.50.162:12201"
        tag: "weatherservice2"  
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
      restart: unless-stopped
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
      restart: unless-stopped
    volumes:
        - ./SeqData:/data