{
 "title": "CAD Envoy Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total, envoy_cluster_name)"
    }
   },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{envoy_cluster_name=\"$cluster\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP请求",
   "type": "timeseries",
   "description": "统计当前服务的请求状况",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "SUM(envoy_cluster_external_upstream_rq{envoy_cluster_name=\"$cluster\"})",
     "legendFormat": "入站请求"
    }
   ]
  },
  {
   "title": "HTTP状态",
   "type": "piechart",
   "description": "统计当前服务的HTTP状态码",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"$cluster\", envoy_response_code_class='2'}\n",
     "legendFormat": "2XX"
    },
    {
     "expr": "envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"$cluster\",envoy_response_code_class='4'}",
     "legendFormat": "4XX"
    },
    {
     "expr": "envoy_cluster_external_upstream_rq_xx{envoy_cluster_name=\"$cluster\",envoy_response_code_class='5'}",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "内存",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated)"
    }
   ]
  },
  {
   "title": "堆栈",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size)"
    }
   ]
  },
  {
   "title": "当前网关数",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(envoy_server_live)" }
   ]
  },
  {
   "title": "当前服务数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total)"
    }
   ]
  },
  {
   "title": "服务运行时长",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(envoy_server_uptime)" }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total)-sum(envoy_cluster_membership_healthy)) == bool 0"
    }
   ]
  },
  {
   "title": "Downstream Total active requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}}({{host}})"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}}({{host}})"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}",
     "legendFormat": "{{zone}}({{host}})"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - in"
    },
    {
     "expr": "irate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - out"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"$cluster\",host=~\"$hosts\"}",
     "legendFormat": "{{zone}}({{host}})"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - in"
    },
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",host=~\"$hosts\"}[1m])",
     "legendFormat": "{{zone}} ({{host}}) - out"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",host=~\"$hosts\"})/count(envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\",host=~\"$hosts\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",host=~\"$hosts\"})/count(envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\",host=~\"$hosts\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}