version: '3'
services:
  city_service:
    build: CityService/
    container_name: city_service
    ports:
      - "8081:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8012", "||", "exit", "1"]
      interval: 2m
      timeout: 10s
      retries: 3